### ISSUE TITLE
Cannot convert value "158047859212581" to type "System.Int32

### ISSUE THREAD

**Issue by Mohamed-abohussein** [TheRealAdamBurford/Create-KeyTab#1]
Hi,

I have to thank you for the great powershell script and your efforts.

When i am creating a keytab file with a new spn, i got the the following error and doesn't add the new spn. do you have any idea why i got this error?
Error:

.\Create-KeyTab.ps1 -Realm test12 -Principal http/AppService -AES256 -File C:\Users
Cannot convert value "158047875042982" to type "System.Int32". Error: "Value was either too large or too small for an Int32."
At C:\Users\test\Create-KeyTab.ps1:524 char:1
+ [byte[]]$timeStamp = Get-BytesBigEndian -BitSize 32 -Value ([int]([Ma ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvalidCastIConvertible
 
AES256: 270BFF2792DB832D7DC9A5D8287D956926341A855B8C6EB61649EE1FC8D44AEA
Principal Type: KRB5_NT_PRINCIPAL
         Realm: TEST12
     User Name: http/AppService
          SALT: TEST12httpAppService
   Keytab File: C:\Users
   Append File: False

Press Enter to Write KeyTab File /Ctrl+C to quit...

PS C:\Users> setspn -L test12
Registered ServicePrincipalNames for CN=test12,OU=test,DC=ad,DC=com:

**Comment by TheRealAdamBurford** [comment]
A couple of things.  First, it looks like you attempted to set the -KVNO option . The value "158047875042982" does not appear in the command used.  The error appears to be with the Key Version number.
e.g. .\Create-KeyTab.ps1 -Realm test12 -Principal http/AppService -AES256 -KVNO 158047875042982

The KVNO needs to be 1-255, the code is written to wrap the KVNO if you used 355, however, it is not written to handle those kinds of numbers. Normally you can just ignore the -KVNO parameter.

Additionally.
The Realm is the DNS name of your domain. Not the NetBIOS name. -REALM AD.COM
The UPN is used for authentication and KeyTab files not an SPN.
The script does not set SPN or UPN. It does not use AD.
If you use the -FILE parameter, you can't just point it at a folder. You have to specify a complete name. c:\users\login.keytab or whatever you want to call the file. If you don't use the -FILE parameter it will write the keytab to the current folder.

**Comment by matherm-aboehm** [comment]
The error message which @Mohamed-abohussein had showed, has nothing to do with the KVNO option. It clearly shows line 531 of your script "`[byte[]]$timeStamp = Get-BytesBigEndian -BitSize 32 -Value ([int]([Ma ...`", which tries to set the $timeStamp value with the current time. But this can't work on localized Windows systems.

You need to use `[decimal]::Parse` there, e.g.:
`[byte[]]$timeStamp = Get-BytesBigEndian -BitSize 32 -Value ([int]([Math]::Truncate([decimal]::Parse((Get-Date(Get-Date).ToUniversalTime() -UFormat %s)))))`

So, as this issue is present, please reopen this issue.

P.S.: The mentioned line number in the error message isn't necessarily the actual line number of the current script file. This can be different due to versioning (if you script has changed since this error) or optimizations from the script engine. It only shows the actually executed line number in the buffer of the execution engine. It is better to look at the actual error and corresponding text line.

**Comment by TheRealAdamBurford** [comment]
Per matherm-aboehm, updated script with [decimal]::parse to correct timestamp error with localized versions of Windows.
